accounting_tech/urls.py
from django.conf.urls import url

from .views import *
from django.urls import path, include
from .views import ListOfEquipment, EquipmentUpdateView, list_equipment_employee, \
    RequestToRepairList, room_form, departament_form, position_form

urlpatterns = [
    path('', ListOfEquipment.as_view(), name='home'),
    path('equipment/<int:pk>/edit/',
         EquipmentUpdateView.as_view(), name='edit_equipment'),
    path('employees/<int:pk>/edit/',
         EmployeeUpdateView.as_view(), name='edit_employee'),
    path('equipment/new/',
         EquipmentCreateView.as_view(), name='create_equipment'),
    path('employee/equipment/<int:pk>/',
         list_equipment_employee, name='list_equipment_employee'),
    path('employee/new/',
         EmployeeCreateView.as_view(), name='create_employee'),
    path('employees/', EmployeesList.as_view(), name='employees_list'),
    path('request-repair/new/',
         RequestToRepairCreateView.as_view(), name='create_request_to_repair'),
    path('report-request-repair/new/',
         ReportRequestToRepairCreateView.as_view(), name='create_report_request_to_repair'),
    path('request-repair', RequestToRepairList.as_view(), name='list_request_to_repair'),
    path('request-repair/<int:pk>/', RequestToRepairDetail.as_view(), name='detail_request-repair'),
    path('print-request-repair/<int:pk>/', PrintRequestRepairToPdf.as_view(), name='print_request-repair'),
    path('print-request-list', ReportRequestToRepairListView.as_view(), name='request-to-repair-list'),
    path('acquisition/new/',
         AcquisitionCreateView.as_view(), name='create_acquisition'),
    path('acquisition', AcquisitionList.as_view(), name='list_acquisition'),
    path('register', EmployeeRegisterView.as_view(), name='register_employee'),
    path('position/new/', position_form, name='create_position'),
    path('departament/new/', departament_form, name='create_departament'),
    path('room/new/', room_form, name='create_room'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

asup_corp_site/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('', include('accounting_tech.urls')),
]

accounting_tech/models.py
from django.db import models, migrations
from django.urls import reverse


class Position(models.Model):
    position_name = models.CharField(max_length=50, blank=False, verbose_name='Должность')

    def __str__(self):
        return self.position_name

    class Meta:
        verbose_name = 'Должность'
        verbose_name_plural = "Должности"


class Departament(models.Model):
    departament_name = models.CharField(max_length=50, blank=False, verbose_name='Отдел')

    def __str__(self):
        return self.departament_name

    class Meta:
        verbose_name = 'Отдел'
        verbose_name_plural = "Отделы"


class Room(models.Model):
    room_name = models.CharField(max_length=50, blank=False, verbose_name='Кабинет')

    def __str__(self):
        return self.room_name

    class Meta:
        verbose_name = 'Кабинет'
        verbose_name_plural = "Кабинеты"


class Employees(models.Model):
    name = models.CharField(max_length=50, blank=False, verbose_name='Имя')
    last_name = models.CharField(max_length=50, blank=False, verbose_name='Фамилия')
    surname = models.CharField(max_length=50, blank=False, verbose_name='Отчество')
    fio = models.CharField(max_length=150, blank=False, verbose_name='Ф.И.О.(Полностью)')
    phone = models.CharField(max_length=20, blank=True, verbose_name='Телефон')
    pin_code = models.IntegerField(blank=False, verbose_name='Пинкод')
    post = models.ForeignKey(Position, on_delete=models.SET_NULL, null=True, verbose_name="Должность")
    dept = models.ForeignKey(Departament, on_delete=models.SET_NULL, null=True, verbose_name="Отдел")
    room = models.ForeignKey(Room, on_delete=models.SET_NULL, null=True, verbose_name="Кабинет")

    def __str__(self):
        return self.fio

    class Meta:
        verbose_name = 'Работники'
        verbose_name_plural = "Работники"


class Equipment(models.Model):
    name = models.CharField(max_length=50, blank=False, verbose_name='Наименование')
    description = models.CharField(max_length=100, blank=True, verbose_name='Описание')
    inventory_number = models.CharField(max_length=100, blank=True, verbose_name='ИНВ №')
    ip_address = models.GenericIPAddressField(null=True, blank=True, verbose_name='IP адрес')
    date_bought = models.DateField(blank=False, verbose_name='Дата постановки')
    worker = models.ForeignKey(Employees, on_delete=models.SET_NULL, null=True, verbose_name='Сотрудник')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Техника'
        verbose_name_plural = "Техника"

    def get_absolute_url(self):
        return reverse('detail_equipment', kwargs={'pk': self.pk})


class RequestToRepair(models.Model):
    complainant = models.ForeignKey(Employees, on_delete=models.SET_NULL, null=True, verbose_name='Заявитель')
    inventory_number = models.CharField(max_length=50, blank=False, verbose_name='ИНВ №')
    phone = models.CharField(max_length=20, blank=False, verbose_name='Телефон')
    location = models.CharField(max_length=100, blank=False, verbose_name='Местонахождение')
    timestamp = models.DateTimeField(auto_now=True, verbose_name='Время создания заявки')
    description_failure = models.TextField(max_length=200, blank=True, verbose_name='Краткое описание неисправности')
    is_repaired = models.BooleanField(default=False, verbose_name='выполнено')

    def __str__(self):
        return self.complainant.fio

    class Meta:
        verbose_name = 'Заявку на ремонт'
        verbose_name_plural = "Заявки на ремонт"


class ReportRequestToRepair(models.Model):
    request_to_repair = models.ForeignKey(RequestToRepair, on_delete=models.CASCADE, null=True, verbose_name='Заявитель', limit_choices_to={'is_repaired': False})
    fio_executor = models.CharField(max_length=150, blank=False, verbose_name='ФИО исполнителя')
    post = models.CharField(max_length=100, blank=False, verbose_name='Должность исполнителя')
    time_field = models.DateTimeField(auto_now=True, verbose_name='Дата и время')
    report = models.TextField(max_length=600, blank=False, verbose_name='Отчет')

    def __str__(self):
        return self.request_to_repair.complainant.fio

    class Meta:
        verbose_name = 'Отчет по заявке на ремонт'
        verbose_name_plural = 'Отчеты по заявкам на ремонт'


class Acquisition(models.Model):
    complainant = models.ForeignKey(Employees, on_delete=models.SET_NULL, null=True, verbose_name='Заявитель')
    phone = models.CharField(max_length=20, blank=True, verbose_name='Телефон')
    description_acquisition = models.TextField(max_length=100, blank=True, verbose_name='Краткое описание заявки')
    timestamp = models.DateTimeField(auto_now=True, verbose_name='Время создания заявки')

    def __str__(self):
        return self.complainant.fio

    class Meta:
        verbose_name = 'Заявку на приобретение'
        verbose_name_plural = 'Заявки на приобретение'

accounting_tech/forms.py
from django.forms import ModelForm
from .models import Room, Departament, Position, RequestToRepair


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = ['room_name']


class DepartamentForm(ModelForm):
    class Meta:
        model = Departament
        fields = ['departament_name']


class PositionForm(ModelForm):
    class Meta:
        model = Position
        fields = ['position_name']


class RequestForm(ModelForm):
    class Meta:
        model = RequestToRepair
        fields = ['complainant', 'is_repaired']

    def __init__(self, *args, **kwargs):
        super(RequestForm, self).__init__(*args, **kwargs)
        self.fields['is_repaired'].queryset = RequestToRepair.objects.filter(is_repaired=False)

accounting_tech/views.py
from urllib.parse import urlparse
from re import match
from django_filters.views import FilterView
from .filters import EquipmentFilter, ReportRequestToRepairFilter, EmployeesFilter
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, CreateView, ListView, UpdateView
from django.views.generic.base import View
from django.core import serializers

from accounting_tech.forms import RoomForm, DepartamentForm, PositionForm, RequestForm
from .models import Equipment, Employees, RequestToRepair, \
    Acquisition, ReportRequestToRepair
from .render_to_pdf import render_to_pdf


@method_decorator(login_required, name='dispatch')
class ListOfEquipment(FilterView):
    """
    This class working with list of Equipment.
    For filtering it using 3rd-party django_filters
    """
    model = Equipment
    template_name = 'accounting_tech/home.html'
    paginate_by = 10
    filterset_class = EquipmentFilter


@method_decorator(login_required, name='dispatch')
class EquipmentCreateView(CreateView):
    """In this class we're creating new kind od Equipment."""
    model = Equipment
    template_name = 'accounting_tech/create_equipment.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('home')


@method_decorator(login_required, name='dispatch')
class EmployeesList(FilterView):
    """
    This class working with list of Employees.
    For filtering it using 3rd-party django_filters
    """
    model = Employees
    template_name = 'accounting_tech/employees_list.html'
    filterset_class = EmployeesFilter


@method_decorator(login_required, name='dispatch')
class EmployeeCreateView(CreateView):
    """In this class we're creating new kind od Equipment."""
    model = Employees
    template_name = 'accounting_tech/create_employee.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('employees_list')


class EmployeeRegisterView(CreateView):  # register new Employee same as EmployeeCreateView
    model = Employees
    template_name = 'accounting_tech/register.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('employees_list')


def list_equipment_employee(request, pk):
    """

    :param request: Come from javascript
    :param pk: Employee id
    :return: All equipment that employee have
    """
    equipment_list_of_worker_query_obj = list(Equipment.objects.filter(worker=pk))
    pin_code_of_worker_query_obj = list(Employees.objects.filter(id=pk))
    equipment_list_of_worker = serializers.serialize(
        'json', pin_code_of_worker_query_obj + equipment_list_of_worker_query_obj)
    return HttpResponse(equipment_list_of_worker)


@method_decorator(login_required, name='dispatch')
class EmployeeUpdateView(UpdateView):
    """In this class we're updating employees."""
    model = Employees
    template_name = 'accounting_tech/edit_employee.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('employees_list')


@method_decorator(login_required, name='dispatch')
class EquipmentUpdateView(UpdateView):
    """In this class we're updating equipment."""
    model = Equipment
    template_name = 'accounting_tech/edit_equipment.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('home')


class RequestToRepairCreateView(CreateView):
    """In this class we're creating new request to repair."""
    model = RequestToRepair
    template_name = 'accounting_tech/create_request_to_repair.html'
    fields = ['complainant', 'inventory_number',
              'phone', 'location', 'description_failure']

    def form_valid(self, form):
        """

        :param form: Form data
        :return: If form data valid then redirect to success_url else redirect to home
        """
        if match(r'^[0-9]-[0-9]{5}$', form.data['inventory_number']):
            form.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return redirect('home')

    def get_success_url(self):
        """
        It send notification if data is valid
        :return: redirect to home
        """
        from notifications.signals import notify
        from django.contrib.auth.models import User, Group
        notify.send(User.objects.get(username='Admin'), recipient=Group.objects.get(name='notify'), verb='New request')
        return reverse_lazy('home')


class ReportRequestToRepairCreateView(CreateView):
    """In this class we're creating new report."""
    model = ReportRequestToRepair
    template_name = 'accounting_tech/create_report_request_to_repair.html'
    fields = '__all__'

    def form_valid(self, form):
        form.save()
        request_to_repair = RequestToRepair.objects.get(id=int(form.data['request_to_repair']))
        request_to_repair.is_repaired = True
        request_to_repair.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('list_request_to_repair')


@method_decorator(login_required, name='dispatch')
class RequestToRepairList(ListView):
    """:returns list requests to repair"""
    model = RequestToRepair

    def get_queryset(self):
        return self.model.objects.filter(is_repaired=False)

    template_name = 'accounting_tech/list_request_to_repair.html'


@method_decorator(login_required, name='dispatch')
class RequestToRepairDetail(DetailView):
    """:returns detail info about request to repair"""
    model = RequestToRepair
    template_name = 'accounting_tech/detail_request_to_repair.html'


class PrintRequestRepairToPdf(View):
    """
    This class using for print detail request to repair
    """

    def get(self, request, *args, **kwargs):
        requests = RequestToRepair.objects.filter(id=kwargs['pk'])
        from django.conf import settings
        data = {
            'root': settings.PDF_FONT_PATH,
            'requests': requests,
        }
        pdf = render_to_pdf('accounting_tech/print_request_to_repair.html', data)
        return HttpResponse(pdf, content_type='application/pdf')


class AcquisitionCreateView(CreateView):
    """This create new one of request acquisition"""
    model = Acquisition
    template_name = 'accounting_tech/create_acquisition.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('home')


@method_decorator(login_required, name='dispatch')
class AcquisitionList(ListView):
    """List all acquisitions"""
    model = Acquisition
    template_name = 'accounting_tech/list_acquisition.html'


class FormReturnRelativePath:
    """Because i repeated that code from time to time .
    I create this class.
    It return path  relative of function, and save form.
    """

    def __init__(self, request, model_form, template):
        self.request = request
        self.model_form = model_form
        self.template = template

    def return_relative(self):
        if self.request.method == 'POST':
            form = self.model_form(self.request.POST)
            url = urlparse(self.request.POST['referrer'])
            if form.is_valid():
                form.save()
                if url:
                    if reverse('create_employee') == url.path:
                        return HttpResponseRedirect(reverse('create_employee'))
                    elif reverse('register_employee') == url.path:
                        return HttpResponseRedirect(reverse('register_employee'))
                    else:
                        return HttpResponseRedirect(url.path)

        else:
            form = self.model_form()
        return render(self.request, self.template, {'form': form})


def room_form(request):
    template = 'accounting_tech/create_room.html'
    fck = FormReturnRelativePath(request, RoomForm, template)
    return fck.return_relative()


def departament_form(request):
    template = 'accounting_tech/create_departament.html'
    fck = FormReturnRelativePath(request, DepartamentForm, template)
    return fck.return_relative()


def position_form(request):
    template = 'accounting_tech/create_position.html'
    fck = FormReturnRelativePath(request, PositionForm, template)
    return fck.return_relative()


class ReportRequestToRepairListView(FilterView):
    """List all requests to repair"""
    model = ReportRequestToRepair
    template_name = 'accounting_tech/report_request_to_repair_list.html'
    paginate_by = 10
    ordering = ['-time_field']
    filterset_class = ReportRequestToRepairFilter

accounting_tech/templates/accounting_tech/base-new.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/bootstrap-min.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,900&display=swap&subset=cyrillic,cyrillic-ext"
        rel="stylesheet">
  <link rel="stylesheet" href= {% static 'css/main-new.css' %}>
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
  {% block datepicker %}
  {% endblock %}
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

accounting_tech/templates/accounting_tech/create_departament.html
{% extends 'accounting_tech/base-new.html' %}
{% block title %}
  Ввод нового отдела
{% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="entry-wrap">
    <div class="container">
      <div class="row justify-content-center flex-column vh-100">
        <div class="align-self-center col-lg-6 col-10">
          <h2 class="entry-wrap__title">Ввод нового отдела</h2>
          <form class="position" action="" method="post">{% csrf_token %}
            {{ form|crispy }}
            <input class="entry-wrap__submit" type="submit" value="Применить изменения"/>
            <input onclick="window.location=document.referrer;" class="entry-wrap__comeback" type="button" value="Вернуться"/>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script src="{% static  'formsRoomPostDepRoom.js' %}"></script>
{% endblock %}

accounting_tech/templates/accounting_tech/create_equipment.html
{% extends 'accounting_tech/base-new.html' %}
{% load crispy_forms_tags %}
{% block datepicker %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
          integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
          crossorigin="anonymous"></script>
  <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
  <script src="https://unpkg.com/gijgo@1.9.13/js/messages/messages.ru-ru.js" type="text/javascript"></script>
  <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css"/>
{% endblock %}
{% block title %}
  Список отчетов
{% endblock %}
{% block content %}
  {% include 'accounting_tech/top-menu.html' %}
  {% include 'accounting_tech/top-nav.html' %}
  <h2 class="home-body__header">Ввод данных</h2>
  <div class="container">
    <div class="row">
      <form class="form-edit__entry" action="" method="post">{% csrf_token %}
        {{ form|crispy }}
        <input class="form-edit__submit" type="submit" value="Применить изменения"/>
      </form>
    </div>
  </div>
  <script type="text/javascript">
      var datepicker, config;
      config = {
          locale: 'ru-ru',
          format: 'dd.mm.yyyy',
          uiLibrary: 'bootstrap4'
      };
      $(document).ready(function () {
          datepicker = $('#id_date_bought').datepicker(config);
          $('#ddlLanguage').on('change', function () {
              var newLang = $(this).val();
              config.locale = newLang;
              datepicker.destroy();
              datepicker = $('#datepicker').datepicker(config);
          });
      });
  </script>
{% endblock %}

accounting_tech/templates/accounting_tech/create_position.html
{% extends 'accounting_tech/base-new.html' %}
{% block title %}
  Ввод новой должности
{% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="entry-wrap">
    <div class="container">
      <div class="row justify-content-center flex-column vh-100">
        <div class="align-self-center col-lg-6 col-10">
          <h2 class="entry-wrap__title">Ввод новой должности</h2>
          <form class="position" action="" method="post">{% csrf_token %}
            {{ form|crispy }}
            <input class="entry-wrap__submit" type="submit" value="Применить изменения"/>
            <input onclick="window.location=document.referrer;" class="entry-wrap__comeback" type="button" value="Вернуться"/>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script src="{% static  'formsRoomPostDepRoom.js' %}"></script>
{% endblock %}

accounting_tech/templates/accounting_tech/create_room.html
{% extends 'accounting_tech/base-new.html' %}
{% block title %}
  Ввод нового кабинета
{% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="entry-wrap">
    <div class="container">
      <div class="row justify-content-center flex-column vh-100">
        <div class="align-self-center col-lg-6 col-10">
          <h2 class="entry-wrap__title">Ввод нового кабинета</h2>
          <form class="position" action="" method="post">{% csrf_token %}
            {{ form|crispy }}
            <input class="entry-wrap__submit" type="submit" value="Применить изменения"/>
            <input onclick="window.location=document.referrer;" class="entry-wrap__comeback" type="button" value="Вернуться"/>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script src="{% static  'formsRoomPostDepRoom.js' %}"></script>
{% endblock %}

accounting_tech/templates/accounting_tech/edit_equipment.html
{% extends 'accounting_tech/base-new.html' %}
{% load crispy_forms_tags %}
{% block datepicker %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
          integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
          crossorigin="anonymous"></script>
  <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
  <script src="https://unpkg.com/gijgo@1.9.13/js/messages/messages.ru-ru.js" type="text/javascript"></script>
  <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css"/>
{% endblock %}
{% block title %}
  Список отчетов
{% endblock %}
{% block content %}
  {% include 'accounting_tech/top-menu.html' %}
  {% include 'accounting_tech/top-nav.html' %}
  <h2 class="home-body__header">Изменение данных</h2>
  <div class="container">
    <div class="row">
      <form class="form-edit__entry" action="" method="post">{% csrf_token %}
        {{ form|crispy }}
        <input class="form-edit__submit" type="submit" value="Применить изменения"/>
      </form>
    </div>
  </div>
  <script type="text/javascript">
      var datepicker, config;
      config = {
          locale: 'ru-ru',
          format: 'dd.mm.yyyy',
          uiLibrary: 'bootstrap4'
      };
      $(document).ready(function () {
          datepicker = $('#id_date_bought').datepicker(config);
          $('#ddlLanguage').on('change', function () {
              var newLang = $(this).val();
              config.locale = newLang;
              datepicker.destroy();
              datepicker = $('#datepicker').datepicker(config);
          });
      });
  </script>
{% endblock %}

accounting_tech/templates/accounting_tech/home-body.html
{% load notifications_tags %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <h2 class="home-body__header">Список техники стоящей на учете</h2>
    <div class="container-fluid">
        <div class="home-body__filters">
            <h5>Фильтры</h5>
            <form method="get" class="home-body__filters--form">
                {{ filter.form|crispy }}
                <input type="submit"/>
            </form>
        </div>
        <div class="row table-wrap">
            <a href="{% url 'create_equipment' %}" class="button__add-new">Новая запись</a>
            <table class="table table-bordered table-equipment">
                <thead>
                <tr>
                    <th scope="col">Модель</th>
                    <th scope="col">Описание</th>
                    <th scope="col">Дата приобретения</th>
                    <th scope="col">Владелец</th>
                    <th scope="col">IP адрес</th>
                </tr>
                </thead>
                {% for equipmet in equipment_list %}
                    <tr>
                        <th scope="row">
                            <a class="btn button__edit" href="{% url 'edit_equipment' equipmet.id %}">
                                <svg class="feather feather-edit sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg"
                                     width="24"
                                     height="24"
                                     viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                     stroke-linecap="round"
                                     stroke-linejoin="round" aria-hidden="true">
                                    <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
                                    <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
                                </svg>
                            </a>
                            {{ equipmet.name }}
                        </th>
                        <td>{{ equipmet.description }}</td>
                        <td>{{ equipmet.date_bought }}</td>
                        <td>{{ equipmet.worker.fio }}</td>
                        <td>{{ equipmet.ip_address }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <script>
        let filterName = document.querySelector('#div_id_name').children[0];
        let filterYear = document.querySelector('#div_id_date_bought').children[0];
        filterName.textContent = 'по модели';
        filterYear.textContent = 'по году ГГГГ';
        document.querySelector('.home-body__filters--form').children[2].value = 'Применить фильтры';
    </script>
{% endblock %}

accounting_tech/templates/accounting_tech/home.html
{% extends 'accounting_tech/base-new.html' %}
{% block title %}
    список техники
{% endblock %}
{% block content %}
    {% include 'accounting_tech/top-menu.html' %}
    {% include 'accounting_tech/top-nav.html' %}
    {% include 'accounting_tech/home-body.html' %}
{% endblock %}

accounting_tech/templates/accounting_tech/list_acquisition.html
{% extends 'accounting_tech/base-new.html' %}
{% block title %}
    Список заявок на приобретение
{% endblock %}
{% block content %}
  {% include 'accounting_tech/top-menu.html' %}
  {% include 'accounting_tech/top-nav.html' %}
  <h2 class="home-body__header">Список заявок на приобретение</h2>
  <div class="container-fluid">
    <div class="row table-wrap">
      <table class="table table-bordered table-equipment">
        <thead>
        <tr>
          <th scope="col" class="text-center">Заявитель</th>
          <th scope="col" class="text-center">Описание заявки</th>
        </tr>
        </thead>
        {% for acquisition in acquisition_list %}
          <tr>
            <th scope="row" class="text-center">
              {{ acquisition.complainant.fio }}
            </th>
            <td class="text-center">{{ acquisition.description_acquisition }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

accounting_tech/templates/accounting_tech/list_request_to_repair.html
{% extends 'accounting_tech/base-new.html' %}
{% block title %}
    Список заявок на ремонт
{% endblock %}
{% block content %}
    {% include 'accounting_tech/top-menu.html' %}
    {% include 'accounting_tech/top-nav.html' %}
    <h2 class="home-body__header">Список заявок на ремонт</h2>
    <div class="container-fluid">
        <div class="row table-wrap">
            <table class="table table-bordered table-equipment">
                <thead>
                <tr>
                    <th scope="col">Заявитель</th>
                    <th scope="col">ИНВ №</th>
                    <th scope="col">Тел.</th>
                    <th scope="col">Местоположение техники</th>
                </tr>
                </thead>
                {% for req in requesttorepair_list %}
                    <tr>
                        <th scope="row">
                            <a class="btn button__edit" href="{% url 'detail_request-repair' req.id %}">
                                <svg class="feather feather-eye sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg"
                                     width="24"
                                     height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                     stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"
                                     data-reactid="516">
                                    <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                                    <circle cx="12" cy="12" r="3"></circle>
                                </svg>
                            </a>
                            {{ req.complainant.fio }}
                        </th>
                        <td>{{ req.inventory_number }}</td>
                        <td>{{ req.phone }}</td>
                        <td>{{ req.location }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <script>
        const markRead = '/inbox/notifications/mark-all-as-read/';
        let xhr = new XMLHttpRequest();
        xhr.open('GET', markRead);
        xhr.send();
    </script>
{% endblock %}